homehome/mysite/homehome/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # 書籍
    url(r'^$', views.task_list, name='task_list'),   # 一覧
    url(r'^add/$', views.task_edit, name='task_add'),  # 登録
    url(r'^mod/(?P<task_id>\d+)/$', views.task_edit, name='task_mod'),  # 修正
    url(r'^del/(?P<task_id>\d+)/$', views.task_del, name='task_del'),   # 削除
    url(r'^comp_edit/(?P<task_id>\d+)/$', views.comp_edit,name='task_comp_edit'),
]

homehome/mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^', include('homehome.urls', namespace='homehome')),
    url(r'^admin/', admin.site.urls),
]

homehome/mysite/homehome/models.py
from django.db import models

from django.utils import timezone

class Task(models.Model):
    """本日のミッション"""
    title= models.CharField(max_length=200)
    contents = models.TextField('タスク内容', blank=True)
    point = models.IntegerField('点数', default=0)
    pub_date = models.DateField('date published',default=timezone.now)
    is_completed = models.IntegerField(default=0)
    def __str__(self):
        return self.comment

homehome/mysite/homehome/forms.py
from django.forms import ModelForm
from .models import Task


class TaskForm(ModelForm):
    """タスクのフォーム"""
    class Meta:
        model = Task
        fields = ('title', 'contents', 'point','pub_date' )

homehome/mysite/homehome/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.http import HttpResponse

from .models import Task
from .forms import TaskForm


def task_list(request):
    """タスクの一覧"""
    # return HttpResponse('書籍の一覧')
    tasks = Task.objects.all().order_by('pub_date')
    context = {
        'tasks' : tasks
    }
    return render(request,
                  'homehome/task_list.html',
                  context)         # テンプレートに渡すデータ

def task_edit(request, task_id=None):
    """タスクの編集"""
    if task_id:   # book_id が指定されている (修正時)
            task = get_object_or_404(Task, id=task_id)
    else:
            task = Task()

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)  # POST された request データからフォームを作成
        if form.is_valid():    # フォームのバリデーション
            task = form.save(commit=False)
            task.save()
            return redirect('homehome:task_list')
    else:    # GET の時
        form = TaskForm(instance=task)  # book インスタンスからフォームを作成
        context = {
            'form' : form,
            'task_id':task_id
        }
        return render(request, 'homehome/task_edit.html', context)

def task_del(request, task_id):
    """書籍の削除"""
#     return HttpResponse('書籍の削除')
    task = get_object_or_404(Task, id=task_id)
    task.delete()
    return redirect('homehome:task_list')

def comp_edit(request, task_id):
    """可否の変更"""
    task = get_object_or_404(Task, id = task_id)
    if task.is_completed == 1:
        task.is_completed = 0
    else:
        task.is_completed = 1
    task.save()
    return redirect('homehome:task_list')

homehome/mysite/homehome/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<title>{% block title %}My books{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block extrahead %}{% endblock %}
</head>
<body>
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
</body>
</html>

homehome/mysite/homehome/templates/homehome/task_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}書籍の編集{% endblock title %}

{% block content %}
    <h3 class="page-header">書籍の編集</h3>
    {% if task_id %}
    <form action="{% url 'homehome:task_mod' task_id=task_id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <form action="{% url 'homehome:task_add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'homehome:task_list' %}" class="btn btn-default fbtn-sm">戻る</a>
{% endblock content %}

homehome/mysite/homehome/templates/homehome/task_list.html
{% extends "base.html" %}

{% block title %}タスクの一覧{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
    <h3 class="page-header">タスクの一覧</h3>
    <a href="{% url 'homehome:task_add' %}" class="btn btn-default btn-sm">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>日付</th>
          <th>タイトル</th>
          <th>内容</th>
          <th>点数</th>
          <th>合否</th>
          <th>
            チェック
          </th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        {% for task in tasks %}
        <tr>
          <td>{{ task.pub_date }}</td>
          <td>{{ task.title }}</td>
          <td>{{ task.contents|linebreaksbr }}</td>
          <td>{{ task.point }}</td>
          {% if task.is_completed == 1 %}
          <td>天才イ！</td>
          {% else %}
          <td>これからだア！</td>
          {% endif %}
          <td>
            <a href="{% url 'homehome:task_comp_edit' task_id=task.id %}" class="btn btn-default btn-sm">□</a>
          </td>
          <td>
            <a href="{% url 'homehome:task_mod' task_id=task.id %}" class="btn btn-default btn-sm">修正</a>
            <a href="{% url 'homehome:task_del' task_id=task.id %}" class="btn btn-default btn-sm">削除</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock content %}